import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { z } from "zod";

import {
  CategoryClassificationSchema,
  CategoryMapSchema,
  ConfigProfileSchema,
  DirectoryRuleSchema,
  DirectoryRulesSchema,
  EntryValueSchema,
  GlobalConfigSchema,
  IdentitySchema,
  WhenSchema,
} from "../src/config/schema";

/**
 * Generates one published JSON Schema file per exported Zod schema in `src/config/schema.ts`, using Zod v4's native `z.toJSONSchema()` — no separate `zod-to-json-schema` dependency.
 *
 * Deliberately uses `io: "input"`, not the default `"output"`: `"output"` reflects the *parsed* shape, where a field with a `.default(...)` (e.g. `Identity.allowAmbientCredential`) is treated as always-present and therefore emitted as `required`. That's wrong for a schema meant to validate a config file as *written* by hand or generated by another tool — the field is genuinely optional on input, with the default applied afterwards. `"input"` reflects the shape a caller may legally write, which is what a published, editor-facing JSON Schema needs to describe.
 */

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(__dirname, "..");
const outDir = path.join(rootDir, "schema");

const schemas: Record<string, z.ZodType> = {
  CategoryMap: CategoryMapSchema,
  WhenCondition: WhenSchema,
  EntryValue: EntryValueSchema,
  ConfigProfile: ConfigProfileSchema,
  DirectoryRule: DirectoryRuleSchema,
  DirectoryRules: DirectoryRulesSchema,
  GlobalConfig: GlobalConfigSchema,
  Identity: IdentitySchema,
  CategoryClassification: CategoryClassificationSchema,
};

function main(): void {
  fs.mkdirSync(outDir, { recursive: true });

  for (const [name, schema] of Object.entries(schemas)) {
    const jsonSchema = z.toJSONSchema(schema, { io: "input" });
    // A placeholder $id, later rewritten to a version-pinned GitHub Release asset URL by scripts/stamp-schema-ids.mjs at publish time — never left pointing at nothing, and never guessed at a real tag here, since this script has no notion of a release tag.
    const withId = { $id: `https://github.com/ExaDev/claude-use/schema/${name}.schema.json`, ...jsonSchema };
    const outPath = path.join(outDir, `${name}.schema.json`);
    fs.writeFileSync(outPath, `${JSON.stringify(withId, null, 2)}\n`);
    console.log(`Wrote ${path.relative(rootDir, outPath)}`);
  }
}

main();
